resources:
  - name: super-app-inedostup
    type: git
    source:
      branch: ci
      uri: https://github.com/iuriinedostup/concourse-tutorial.git

jobs:
  - name: Testing
    plan:
    - get: super-app-inedostup
      trigger: true
    - aggregate:
      - task: lint
        file: super-app-inedostup/ci/tasks/lint.yml

      - task: unit
        file: super-app-inedostup/ci/tasks/unit.yml

  - name: Building and integration test
    plan:
    - get: super-app-inedostup
      passed: ['Testing']
      trigger: true

    - task: build
      file: super-app-inedostup/ci/tasks/build.yml

    - task: integration test
      file: super-app-inedostup/ci/tasks/integration.yml
